-- [[ VANITY-ANTICHEAT CONFIGURATION V2.5 ROBLOX ENHANCED ]]
local CONFIG = {}

CONFIG.VERSION = "2.5"
CONFIG.LAST_UPDATED = os.date("%Y-%m-%d")

CONFIG.ANOMALY_THRESHOLD = 5.0
CONFIG.WARNING_ANOMALY_THRESHOLD = 7.5
CONFIG.CRITICAL_ANOMALY_THRESHOLD = 10.0
CONFIG.ANOMALY_DECAY_RATE = 0.1
CONFIG.MAX_ANOMALY_SCORE = 20.0
CONFIG.ANOMALY_MULTIPLIER = 1.5

CONFIG.REPUTATION_MIN = -100
CONFIG.REPUTATION_MAX = 100
CONFIG.REPUTATION_DECAY_RATE = 0.05
CONFIG.REPUTATION_GAIN_RATE = 0.1
CONFIG.REPUTATION_PENALTY_MULTIPLIER = 1.2

CONFIG.DISCORD_WEBHOOK_URL = "https://discord.com/api/webhooks/YOUR_WEBHOOK_URL"
CONFIG.DISCORD_ALERT_WEBHOOK_URL = "https://discord.com/api/webhooks/YOUR_ALERT_WEBHOOK_URL"
CONFIG.DISCORD_LOG_WEBHOOK_URL = "https://discord.com/api/webhooks/YOUR_LOG_WEBHOOK_URL"

CONFIG.NOCLIP_DETECTION = true
CONFIG.WALLHACK_DETECTION = true
CONFIG.AIMBOT_DETECTION = true
CONFIG.ESP_DETECTION = true
CONFIG.INFINITE_JUMP_DETECTION = true
CONFIG.FLIGHT_DETECTION = true
CONFIG.SPEED_DETECTION = true
CONFIG.TELEPORT_DETECTION = true
CONFIG.KILL_AURA_DETECTION = true
CONFIG.GOD_MODE_DETECTION = true

CONFIG.SPEED_LIMIT = 50
CONFIG.DAMAGE_THRESHOLD = 100
CONFIG.SPEED_CHECK_INTERVAL = 0.1
CONFIG.SPEED_VIOLATION_THRESHOLD = 3
CONFIG.VERTICAL_SPEED_LIMIT = 100
CONFIG.ACCELERATION_LIMIT = 50
CONFIG.ROTATION_SPEED_LIMIT = 720
CONFIG.MAX_TELEPORT_DISTANCE = 1000
CONFIG.POSITION_CHECK_INTERVAL = 0.1
CONFIG.VELOCITY_HISTORY_SIZE = 10
CONFIG.MAX_ACCELERATION = 100
CONFIG.MAX_DECELERATION = 100
CONFIG.MOVEMENT_PREDICTION_WINDOW = 0.5

CONFIG.MAX_DAMAGE_PER_SECOND = 200
CONFIG.MIN_HIT_INTERVAL = 0.1
CONFIG.MAX_HITS_PER_SECOND = 10
CONFIG.MAX_RANGE_MULTIPLIER = 1.5
CONFIG.DAMAGE_VERIFICATION = true
CONFIG.COMBAT_LOG_RETENTION = 300
CONFIG.MAX_HEALTH_MULTIPLIER = 1.5
CONFIG.MAX_HEALTH_REGEN_RATE = 10
CONFIG.HEALTH_CHECK_INTERVAL = 0.2
CONFIG.HEALTH_HISTORY_SIZE = 20
CONFIG.MAX_DAMAGE_DISTANCE = 100

CONFIG.REMOTE_EVENT_THROTTLING = true
CONFIG.MAX_REMOTE_CALLS = 100
CONFIG.INSTANCE_CREATION_LIMIT = 50
CONFIG.PROPERTY_CHANGE_LIMIT = 100
CONFIG.ANTI_REMOTE_SPAM = true
CONFIG.SECURE_INSTANCE_CHECK = true

CONFIG.PHYSICS_VALIDATION = true
CONFIG.GRAVITY_CHECK = true
CONFIG.COLLISION_CHECK = true
CONFIG.CAMERA_LIMITS = true
CONFIG.POSITION_VALIDATION = true
CONFIG.TELEPORT_VALIDATION = true

CONFIG.PATTERN_DETECTION = true
CONFIG.BEHAVIOR_ANALYSIS = true
CONFIG.MACHINE_LEARNING = false
CONFIG.SIGNATURE_DETECTION = true
CONFIG.MEMORY_SCANNING = true
CONFIG.HASH_VERIFICATION = true

CONFIG.AUTO_BAN = true
CONFIG.AUTO_KICK = true
CONFIG.WARNING_SYSTEM = true
CONFIG.PROGRESSIVE_PUNISHMENT = true
CONFIG.PUNISHMENT_DECAY = 7 * 24 * 3600
CONFIG.MAX_WARNINGS = 3

CONFIG.LOG_LEVEL = "DETAILED"
CONFIG.LOG_RETENTION = 30 * 24 * 3600
CONFIG.MONITOR_CHAT = true
CONFIG.MONITOR_TOOLS = true
CONFIG.MONITOR_REMOTES = true
CONFIG.MONITOR_INSTANCES = true

CONFIG.ASYNC_PROCESSING = true
CONFIG.BATCH_PROCESSING = true
CONFIG.OPTIMIZATION_LEVEL = "HIGH"
CONFIG.MAX_CHECKS_PER_FRAME = 20
CONFIG.LOAD_BALANCING = true
CONFIG.OPTIMIZATION_INTERVAL = 60
CONFIG.MEMORY_THRESHOLD = 0.9
CONFIG.CPU_THRESHOLD = 0.8
CONFIG.MAX_CONCURRENT_MONITORS = 50
CONFIG.BATCH_SIZE = 10

CONFIG.SECURITY_LEVEL = "HIGH"
CONFIG.STRICT_MODE = true
CONFIG.PARANOID_MODE = false
CONFIG.LEARNING_MODE = false

CONFIG.APPEAL_SYSTEM = true
CONFIG.APPEAL_COOLDOWN = 7 * 24 * 3600
CONFIG.MAX_APPEALS = 3
CONFIG.APPEAL_REVIEW_TIME = 48 * 3600
CONFIG.AUTO_APPEAL_THRESHOLD = 0.2
CONFIG.APPEAL_EVIDENCE_REQUIRED = true

CONFIG.ADMIN_IMMUNITY = true
CONFIG.ADMIN_LOGGING = true
CONFIG.ADMIN_NOTIFICATION = true
CONFIG.ADMIN_OVERRIDE = true
CONFIG.ADMIN_COMMANDS = true
CONFIG.ADMIN_GROUPS = {
    ["GameAdmins"] = true,
    ["Moderators"] = true,
    ["Developers"] = true
}
CONFIG.ADMIN_NOTIFICATION_LEVEL = "ALL"
CONFIG.ADMIN_OVERRIDE_COOLDOWN = 300
CONFIG.ADMIN_ACTION_LOGGING = true

CONFIG.WHITELIST_ENABLED = true
CONFIG.WHITELIST_GROUPS = {
    ["GameAdmins"] = true,
    ["Moderators"] = true,
    ["Developers"] = true
}

CONFIG.REPORT_SYSTEM = true
CONFIG.MAX_REPORTS = 10
CONFIG.REPORT_COOLDOWN = 300
CONFIG.AUTO_REPORT_REVIEW = true

CONFIG.BAN_DURATION = 7 * 24 * 3600
CONFIG.TEMP_BAN_DURATION = 24 * 3600
CONFIG.BAN_APPEAL_COOLDOWN = 14 * 24 * 3600
CONFIG.MAX_WARNINGS_BEFORE_BAN = 3
CONFIG.WARNING_EXPIRY = 7 * 24 * 3600
CONFIG.BAN_DATA_BACKUP_INTERVAL = 3600

CONFIG.RATE_LIMIT_WINDOW = 60
CONFIG.MAX_PACKET_SIZE = 1024 * 100
CONFIG.MIN_REQUEST_INTERVAL = 0.1
CONFIG.NETWORK_TIMEOUT = 5
CONFIG.MAX_CONCURRENT_REQUESTS = 10
CONFIG.NETWORK_ANOMALY_THRESHOLD = 0.8

CONFIG.DATA_STORE_RETRY_ATTEMPTS = 3
CONFIG.DATA_STORE_RETRY_DELAY = 2
CONFIG.BACKUP_STORE_SUFFIX = "_backup"
CONFIG.DATA_CLEANUP_INTERVAL = 24 * 3600
CONFIG.MAX_STORED_VIOLATIONS = 1000
CONFIG.MAX_STORED_ACTIONS = 500

CONFIG.BEHAVIOR_ANALYSIS_INTERVAL = 1
CONFIG.PATTERN_MATCH_TOLERANCE = 0.2

CONFIG.INSTANCE_CHECK_INTERVAL = 0.5
CONFIG.SUSPICIOUS_INSTANCES = {
    "LocalScript",
    "RemoteEvent",
    "RemoteFunction",
    "ModuleScript"
}
CONFIG.PROTECTED_INSTANCES = {
    "Workspace",
    "Players",
    "ReplicatedStorage"
}

CONFIG.NOTIFICATION_THROTTLE = 1
CONFIG.MAX_NOTIFICATIONS = 5
CONFIG.NOTIFICATION_DURATION = 5
CONFIG.NOTIFICATION_FADE = 0.5
CONFIG.CRITICAL_NOTIFICATION_DURATION = 10
CONFIG.NOTIFICATION_QUEUE_SIZE = 20

CONFIG.MAX_JUMP_POWER = 50
CONFIG.MAX_WALK_SPEED = 16

return CONFIG
